version: 2

sources:
  - name: northwind_kondado
    schema: northwind_kondado
    description: This is the Northwind erp postgres database replica.
    tables:
      - name: categories
        description: This is the product category table.
        columns:
          - name: category_id
            description: Primary key of the product category table.
            tests:
              - unique
              - not_null
          - name: category_name
            description: Primary key of the product category table.
            tests:
              - not_null

      - name: customers
        description: This is the customer table. It includes informations about Northwind customers.
        columns:
          - name: customer_id
            description: Primary key of the customer table.
            tests:
              - unique
              - not_null
          - name: company_name
            description: This is the company's name.
            tests:
              - unique
              - not_null
          - name: city
            description: This is the city of customers.
            tests:
              - not_null   
          - name: region
            description: This is the region of customers.
          - name: country
            description: This is the country of customers.
            tests:
              - not_null  

      - name: employees
        description: This is the employee table.
        columns:
          - name: employee_id
            description: Primary key of the employee table.
            tests:
              - unique            
              - not_null
          - name: first_name
            description: This is the employee's first name.
            tests:          
              - not_null
          - name: last_name
            description: This is the employee's last name.
            tests:          
              - not_null
          - name: city
            description: This is the city of employees.
            tests:
              - not_null   
          - name: region
            description: This is the region of employees.
          - name: country
            description: This is the country of employees.
            tests:
              - not_null  

      - name: order_details
        description: This is the order details table.
        columns:
          - name: order_id
            description: Foreing key of the order table.
            tests:          
              - not_null
          - name: product_id
            description: Foreing key of the product table.
            tests:       
              - not_null
          - name: quantity
            description: This is the quantity of products.
            tests:       
              - not_null
          - name: unit_price
            description: This is the unit price product.
            tests:       
              - not_null
          - name: discount
            description: This is the discount of products.
            tests:       
              - not_null

      - name: orders
        description: This is the order table.
        columns:
          - name: order_id
            description: Primary key of the order table.
            tests:
              - unique          
              - not_null
          - name: customer_id
            description: Foreing key of the customer table.
            tests:      
              - not_null
          - name: employee_id
            description: Foreing key of the employee table.
            tests:      
              - not_null
          - name: ship_via
            description: Foreing key of the shippers table.
            tests:      
              - not_null
          - name: order_date
            description: This is the order date.
            tests:      
              - not_null
          - name: ship_city
            description: This is the city of orders.
            tests:      
              - not_null
          - name: ship_region
            description: This is the region of orders.
          - name: ship_country
            description: This is the country of orders.
            tests:
              - not_null  

      - name: products
        description: This is the product table.
        columns:
          - name: product_id
            description: Primary key of the product table.
            tests:
              - unique          
              - not_null
          - name: supplier_id
            description: Foreing key of the supplier table.
            tests:        
              - not_null
          - name: category_id
            description: Foreing key of the category table.
            tests:        
              - not_null
          - name: product_name
            description: This is the product name.
            tests:        
              - not_null
          - name: unit_price
            description: This is the unit price of the products.
            tests:        
              - not_null
          - name: discontinued
            description: This is the information about discontinued products.
            tests:        
              - not_null

      - name: shippers
        description: This is the shippers table.
        columns:
          - name: shipper_id
            description: Primary key of the shippers table.
            tests:
              - unique          
              - not_null
          - name: company_name
            description: This is the company name of shipper.
            tests:  
              - not_null

      - name: suppliers
        description: This is the suppliers table.
        columns:
          - name: supplier_id
            description: Primary key of the supplier table.
            tests:
              - unique          
              - not_null
          - name: company_name
            description: This is the company name of supplier.
            tests:  
              - not_null
          - name: city
            description: This is the city of supplier.
            tests:
              - not_null   
          - name: region
            description: This is the region of supplier.
          - name: country
            description: This is the country of supplier.
            tests:
              - not_null

      - name: seed_regions
        description: This is an auxiliary table. This is the informations about city, region, country and division of countries by continents.
        columns:
          - name: id
            description: This key references the city and country of each region to give data integrity, as sometimes the same name of a city appears in more than one country.
            tests:
              - unique
              - not_null
          - name: city
            description: This is referring to city information.
            tests:         
              - not_null
          - name: region
            description: This is referring to region information.
            tests:         
              - not_null
          - name: country
            description: This is referring to country information.
            tests:         
              - not_null
          - name: division
            description: This is referring to division of countries by continents.
            tests:         
              - not_null